=== fuunzap/Hajusrakenduste-alused/Hajusrakenduste alused/books.dtd
<!ELEMENT root (Books)>
<!ELEMENT Books (Book+)>
<!ELEMENT Book (#PCDATA|BookID|ISBN|Title|Description|Price|Pages|Year|Language|Category|Authors)*>
<!ELEMENT BookID (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Pages (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Language (#PCDATA)>
<!ELEMENT Category (#PCDATA)>
<!ELEMENT Authors (Author)>
<!ELEMENT Author EMPTY>
<!ATTLIST Author AuthorID NMTOKEN #REQUIRED>
<!ATTLIST Author Firstname NMTOKEN #REQUIRED>
<!ATTLIST Author Lastname NMTOKEN #REQUIRED>

=== fuunzap/Hajusrakenduste-alused/Hajusrakenduste alused/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "books.dtd">
<root>
<Books>
    <Book>
    <BookID>1</BookID>
    <ISBN>978-161729126</ISBN>
    <Title>Pro ASP.NET MVC 4</Title>
    <Description>The ASP.NET MVC 4 Framework is the latest evolution of Microsoft's</Description>
    <Price>38.8500</Price>
    <Pages>500</Pages>
    <Year>2013-01-16</Year>
    <Language>ENG</Language>
    <Category>Web</Category>|
    <Authors>
    <Author AuthorID="2" Firstname="Adam" Lastname="Freeman" />
    </Authors>
    </Book>
        <Book>
        <BookID>1</BookID>
        <ISBN>978-161729126</ISBN>
        <Title>Pro ASP.NET MVC 4</Title>
        <Description>The ASP.NET MVC 4 Framework is the latest evolution of Microsoft's</Description>
        <Price>38.8500</Price>
        <Pages>500</Pages>
        <Year>2013-01-16</Year>
        <Language>ENG</Language>
        <Category>Web</Category>|
        <Authors>
        <Author AuthorID="2" Firstname="Adam" Lastname="Freeman" />
        </Authors>
        </Book>
    </Books>
    </root>
