<!DOCTYPE root [
    <!ELEMENT root (counrty+)>
    <!ELEMENT counrty (name, language, currency)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT language (lang+)>
    <!ELEMENT lang (#PCDATA)>
    <!ATTLIST lang isOfficial CDATA "False">
    <!ELEMENT currency EMPTY>
    <!ATTLIST currency name CDATA #REQUIRED sign CDATA #REQUIRED>
]>

<root>
    <counrty>
        <name>Estonia</name>
        <language>
            <lang isOfficial="True">Estonia</lang>
            <lang>Russian</lang>
            <lang>Finnish</lang>
        </language>
        <currency name="Euro" sign="€"/>
    </counrty>
    <counrty>
        <name>Russia</name>
        <language>
            <lang isOfficial="True">Russian</lang>
            <lang>Russian</lang>
        </language>
        <currency name="Rub" sign="₽"/>
    </counrty>
    <counrty>
        <name>Ukraine</name>
        <language>
            <lang isOfficial="True">Ukrainan</lang>
            <lang>Russian</lang>
        </language>
        <currency name="Grivna" sign="₴"/>
    </counrty>
    <counrty>
        <name>Kazakhstan</name>
        <language>
            <lang isOfficial="True">Kazakh</lang>
            <lang>Russian</lang>
        </language>
        <currency name="Tenge" sign="⍑"/>
    </counrty>
    <counrty>
        <name>Belarus</name>
        <language>
            <lang isOfficial="True">Belaruskiy</lang>
            <lang>Russian</lang>
        </language>
        <currency name="Rub" sign="₽"/>
    </counrty>
    <counrty>
        <name>Poland</name>
        <language>
            <lang isOfficial="True">Poland</lang>
            <lang>Ukraine</lang>
            <lang>Russian</lang>
        </language>
        <currency name="Zloty" sign="zł"/>
    </counrty>
    <counrty>
        <name>Germany</name>
        <language>
            <lang isOfficial="True">Germany</lang>
            <lang>Russian</lang>
            <lang>Ukraine</lang>
        </language>
        <currency name="Euro" sign="€"/>
    </counrty>
    <counrty>
        <name>Türkiye</name>
        <language>
            <lang isOfficial="True">Turkish</lang>
            <lang>Russian</lang>
            <lang>Ukraine</lang>
            <lang>English</lang>
        </language>
        <currency name="Turkish lira" sign="₺"/>
    </counrty>
    <counrty>
        <name>Finland</name>
        <language>
            <lang isOfficial="True">Finnish</lang>
            <lang>Russian</lang>
            <lang>Estonia</lang>
            <lang>English</lang>
        </language>
        <currency name="Dollar" sign="$"/>
    </counrty>
    <counrty>
        <name>Estonia</name>
    <language>
        <lang isOfficial="True">Egypt</lang>
        <lang>Russian</lang>
        <lang>English</lang>
    </language>
    <currency name="Egyptian pound" sign=".ج.م"></currency>
</counrty>
</root>